alias sl = ls
alias l = ls
alias ll = ls -l
alias la = ls -la
alias ldot = ls .*
alias vi = nvim -u NONE
alias vim = nvim -u NORC
alias q = exit
alias cat = open --raw
alias imgcat = wezterm imgcat
# alias man = help
